# -*- coding: utf-8 -*-
"""Untitled21.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usLR68NARB2sHw5EwEMLf_wphgC-jTtK
"""

import pandas as pd
df = pd.read_csv("/content/Ecommerce before cleaninggg.csv")
df

df_columns = pd.DataFrame(df.columns, columns=["column Names"])
df_columns

from tabulate import tabulate
info_list = [[col, df[col].count(),df[col].dtype] for col in df.columns]
info_table = tabulate(info_list, headers=["Column Name","Non-Null count", "Data Type"],tablefmt="grid")
print(info_table)

df.describe()

df_dtypes = pd.DataFrame(df.dtypes, columns=["Data Types"])
df_dtypes

df.rename(columns={"order_date.1":"order_date"}, inplace=True)
df.rename(columns={"ship_date.1":"ship_date"}, inplace=True)

df["order_date"] = pd.to_datetime(df["order_date"], format="mixed", errors="coerce")

df["order_date"] = pd.to_datetime(df["order_date"], format="%d/%m/%y")

df["ship_date"] = pd.to_datetime(df["ship_date"],format="mixed" , errors="coerce")

df["ship_date"] = pd.to_datetime(df["ship_date"], format="%d/%m/%y")

df_dtypes = pd.DataFrame(df.dtypes, columns=["Data Types"])
df_dtypes

mapping = {1: "First Class", 2: "Second Class", 4: "Standard Class"}
df["shipping_type"] = df["shipping_type"].fillna(df["shipping_type"].map(mapping))

info_list = [[col, df[col].count(),df[col].dtype] for col in df.columns]
info_table = tabulate(info_list, headers=["Column Name","Non-Null count", "Data Type"],tablefmt="grid")
print(info_table)

empty_row = df[df.isnull().any(axis=1)]
empty_row

df.shape[0]

df["shipping_type"] = df.apply(lambda row: "Second Class" if row["days_for_shipment_scheduled"]==2
                               else ("Standard Class" if row["days_for_shipment_scheduled"]==4
                                     else row["shipping_type"]), axis=1)

info_list = [[col, df[col].count(),df[col].dtype] for col in df.columns]
info_table = tabulate(info_list, headers=["Column Name","Non-Null count", "Data Type"],tablefmt="grid")
print(info_table)

df.duplicated().sum()

df_columns

df["category_name"] = df["category_name"].str.strip()

df["customer_full_name"] = df["customer_first_name"] + " " + df["customer_last_name"]

df.drop(columns=["customer_first_name","customer_last_name"],inplace=True)

df.isnull().sum()

import matplotlib.pyplot as plt
shipment_scheduled_counts = df["days_for_shipment_scheduled"].value_counts()
shipment_real_counts = df["days_for_shipment_real"].value_counts()
fig, axes = plt.subplots(1, 2, figsize=(12, 6))
axes[0].pie(shipment_scheduled_counts, labels=shipment_scheduled_counts.index, autopct="%1.1f%%", startangle=90)
axes[0].set_title("Days for Shipment Scheduled")
axes[1].pie(shipment_real_counts, labels=shipment_real_counts.index, autopct="%1.1f%%", startangle=90)
axes[1].set_title("Days for Shipment Real")
plt.tight_layout()
plt.show()

category_counts = df["category_name"].value_counts()
plt.bar(category_counts.index, category_counts.values)
plt.xlabel("category_name")
plt.ylabel("Count")
plt.title("category_name Distribution")
plt.show()

"""df.to_csv("Ecommerce after cleaning.csv", index=False)"""

df.to_csv("Cleaning Ecommerce22.csv",index=False)